/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CLASES.jugador;
import CLASES.participa;
import CLASES.preguntas;
import CLASES.rondas;
import CONTROLADORES.ctrlquestions;

/**
 *
 * @author franc
 */
public class jugar extends javax.swing.JFrame {

    /**
     * Creates new form jugar
     */
    public static boolean one, two, three, four;
    private int rondasjugadas;
    public static rondas ronda = null;
    public static participa participacion = null;
    public static preguntas preg = null;
    ctrlquestions CQ = new ctrlquestions();

    public jugar(jugador player) {
        initComponents();
        int acumulado;
        ronda = new rondas();
        participacion = new participa();
        preg = new preguntas();

        rellenarcampos(CQ.pregunta1());

    }

    jugar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void rellenarcampos(preguntas preg1) {
        jLabel1.setText(preg.getPregunta());
        one = false;
        two = false;
        three = false;
        four = false;
        int random;
        String respuesta1x = preg1.getRespuestac();
        String respuesta2x = preg1.getRespuesta1();
        String respuesta3x = preg1.getRespuesta2();
        String respuesta4x = preg1.getRespuesta3();
        for (int i = 4; i <= 4; i = i + 1) {

            switch (i) {

                case 1: {

                    random = (int) (Math.random() * 4 + 1);
                    if (random == 1 && !one) {
                        respuesta1.setText(respuesta1x);
                        one = true;
                    } else if (random == 2 && !two) {
                        respuesta1.setText(respuesta2x);
                        two = true;
                    } else if (random == 3 && !three) {
                        respuesta1.setText(respuesta3x);
                        three = true;
                    } else if (random == 4 && !four) {
                        respuesta1.setText(respuesta4x);
                        four = true;
                    }
                    break;

                }

                case 2: {

                    random = (int) (Math.random() * 4 + 1);
                    if (random == 1 && !one) {
                        respuesta2.setText(respuesta1x);
                        one = true;
                    } else if (random == 2 && !two) {
                        respuesta2.setText(respuesta2x);
                        two = true;
                    } else if (random == 3 && !three) {
                        respuesta2.setText(respuesta3x);
                        three = true;
                    } else if (random == 4 && !four) {
                        respuesta2.setText(respuesta4x);
                        four = true;
                    }

                    break;

                }

                case 3: {

                    random = (int) (Math.random() * 4 + 1);
                    if (random == 1 && !one) {
                        respuesta3.setText(respuesta1x);
                        one = true;
                    } else if (random == 2 && !two) {
                        respuesta3.setText(respuesta2x);
                        two = true;
                    } else if (random == 3 && !three) {
                        respuesta3.setText(respuesta3x);
                        three = true;
                    } else if (random == 4 && !four) {
                        respuesta3.setText(respuesta4x);
                        four = true;
                    }

                    break;

                }
                case 4: {

                    random = (int) (Math.random() * 4 + 1);
                    if (random == 1 && !one) {
                        respuesta4.setText(respuesta1x);
                        one = true;
                    } else if (random == 2 && !two) {
                        respuesta4.setText(respuesta2x);
                        two = true;
                    } else if (random == 3 && !three) {
                        respuesta4.setText(respuesta3x);
                        three = true;
                    } else if (random == 4 && !four) {
                        respuesta4.setText(respuesta4x);
                        four = true;
                    }

                    break;

                }

                default: {

                }

            }//cierra SWITCH
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JRadioButton();
        respuesta2 = new javax.swing.JRadioButton();
        respuesta3 = new javax.swing.JRadioButton();
        respuesta4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        respuesta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        respuesta1.setText("jRadioButton1");

        respuesta2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        respuesta2.setText("jRadioButton2");

        respuesta3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        respuesta3.setText("jRadioButton3");

        respuesta4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        respuesta4.setText("jRadioButton4");
        respuesta4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                respuesta4StateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Respuesta:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Premio Ronda:");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Acumulado:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Ronda Acual");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("1");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("/5");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Siguiente ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(respuesta2)
                                .addComponent(respuesta1)
                                .addComponent(respuesta3)
                                .addComponent(respuesta4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuesta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void respuesta4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_respuesta4StateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_respuesta4StateChanged
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton respuesta1;
    private javax.swing.JRadioButton respuesta2;
    private javax.swing.JRadioButton respuesta3;
    private javax.swing.JRadioButton respuesta4;
    // End of variables declaration//GEN-END:variables
}
